### ISSUE TITLE
Briefcase Failing on Ubuntu 18.04 with Python 3.6

### ISSUE THREAD

**Issue by DonaldKBrown** [beeware/briefcase-template#9]
I'm trying to follow the Quickstart guide to see how this works and if it's the right fit for my project. However, I'm running into an issue when running `python setup.py linux -s`. Here is the output of my whole process:

```
donald@hoth:~$ mkdir briefcase-test
donald@hoth:~$ cd briefcase-test
donald@hoth:~/briefcase-test$ python3 -m venv env
donald@hoth:~/briefcase-test$ source env/bin/activate
(env) donald@hoth:~/briefcase-test$ pip install cookiecutter briefcase
Collecting cookiecutter
  Using cached https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1.6.0-py2.py3-none-any.whl
Collecting briefcase
  Using cached https://files.pythonhosted.org/packages/8d/45/5f2f23bf9e389857b179347acbd2dcd8de10f110218802240ba0bed10979/briefcase-0.2.6-py3-none-any.whl
Collecting requests>=2.18.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting poyo>=0.1.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/ea/6c/62c76c12015f6a1849446fb73da59be1229312c54d6d05068275e52bf29f/poyo-0.4.1-py2.py3-none-any.whl
Collecting click>=5.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting whichcraft>=0.4.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/60/8a/5c52e30e11672f7e3aa61f348ddae443d122bcd96bc8b785ac76dbae944b/whichcraft-0.4.1-py2.py3-none-any.whl
Collecting jinja2>=2.7 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting binaryornot>=0.2.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting jinja2-time>=0.1.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl
Collecting future>=0.15.2 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting setuptools>=40.0 (from briefcase)
  Using cached https://files.pythonhosted.org/packages/66/e8/570bb5ca88a8bcd2a1db9c6246bb66615750663ffaaeada95b04ffe74e12/setuptools-40.2.0-py2.py3-none-any.whl
Collecting voc>=0.1.1 (from briefcase)
  Using cached https://files.pythonhosted.org/packages/d2/bc/e8c769eb7d05f486346103783e78ebe283842dd09038ff5b1fa55cda3ad0/voc-0.1.5-py3-none-any.whl
Collecting pip>=18.0 (from briefcase)
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Collecting boto3>=1.4.4 (from briefcase)
  Using cached https://files.pythonhosted.org/packages/a8/45/810f786ce144bfd19d9f2f700a8cd4358435559a2b88b2c235f7bb3f29df/boto3-1.8.6-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.18.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.18.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.18.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.18.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2>=2.7->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Collecting arrow (from jinja2-time>=0.1.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/e0/86/4eb5228a43042e9a80fe8c84093a8a36f5db34a3767ebd5e1e7729864e7b/arrow-0.12.1.tar.gz
Collecting botocore<1.12.0,>=1.11.6 (from boto3>=1.4.4->briefcase)
  Using cached https://files.pythonhosted.org/packages/52/86/73e2825c9f452f6ea7ebbd715aa4621eb1f5d5e51e37cd2019437535909c/botocore-1.11.6-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.4.4->briefcase)
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3>=1.4.4->briefcase)
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting python-dateutil (from arrow->jinja2-time>=0.1.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.12.0,>=1.11.6->boto3>=1.4.4->briefcase)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->arrow->jinja2-time>=0.1.0->cookiecutter)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: future, MarkupSafe, arrow
  Running setup.py bdist_wheel for future ... error
  Complete output from command /home/donald/briefcase-test/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wtetc5lv/future/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpx4hkp4vupip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for future
  Running setup.py clean for future
  Running setup.py bdist_wheel for MarkupSafe ... error
  Complete output from command /home/donald/briefcase-test/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wtetc5lv/MarkupSafe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1z9t5lispip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for MarkupSafe
  Running setup.py clean for MarkupSafe
  Running setup.py bdist_wheel for arrow ... error
  Complete output from command /home/donald/briefcase-test/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wtetc5lv/arrow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_e9bcpm5pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for arrow
  Running setup.py clean for arrow
Failed to build future MarkupSafe arrow
Installing collected packages: idna, urllib3, chardet, certifi, requests, poyo, click, whichcraft, MarkupSafe, jinja2, binaryornot, six, python-dateutil, arrow, jinja2-time, future, cookiecutter, setuptools, voc, pip, jmespath, docutils, botocore, s3transfer, boto3, briefcase
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for arrow ... done
  Running setup.py install for future ... done
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed MarkupSafe-1.0 arrow-0.12.1 binaryornot-0.4.4 boto3-1.8.6 botocore-1.11.6 briefcase-0.2.6 certifi-2018.8.24 chardet-3.0.4 click-6.7 cookiecutter-1.6.0 docutils-0.14 future-0.16.0 idna-2.7 jinja2-2.10 jinja2-time-0.2.0 jmespath-0.9.3 pip-18.0 poyo-0.4.1 python-dateutil-2.7.3 requests-2.19.1 s3transfer-0.1.13 setuptools-40.2.0 six-1.11.0 urllib3-1.23 voc-0.1.5 whichcraft-0.4.1
(env) donald@hoth:~/briefcase-test$ cookicutter https://github.com/pybee/briefcase-template

Command 'cookicutter' not found, did you mean:

  command 'cookiecutter' from deb cookiecutter

Try: sudo apt install <deb name>

(env) donald@hoth:~/briefcase-test$ cookiecutter https://github.com/pybee/briefcase-template
You've downloaded /home/donald/.cookiecutters/briefcase-template before. Is it okay to delete and re-download it? [yes]: yes
app_name [appname]: helloworld
formal_name [App Name]: Hello World
description [An app that does lots of stuff]: 
author [Jane Developer]: 
author_email [jane@example.com]: 
bundle [com.example]: 
Select license:
1 - BSD license
2 - MIT license
3 - Apache Software License
4 - GNU General Public License v2 (GPLv2)
5 - GNU General Public License v2 or later (GPLv2+)
6 - GNU General Public License v3 (GPLv3)
7 - GNU General Public License v3 or later (GPLv3+)
8 - Other
Choose from 1, 2, 3, 4, 5, 6, 7, 8 [1]: 
Select gui_framework:
1 - Toga
2 - None
Choose from 1, 2 [1]: 
(env) donald@hoth:~/briefcase-test$ cd helloworld
(env) donald@hoth:~/briefcase-test/helloworld$ python setup.py linux -s
running linux
 * Writing application template...
Template Python-Linux-template succesfully updated.
Project template: /home/donald/.cookiecutters/Python-Linux-template
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django==0.3.0.dev9',
  File "/home/donald/briefcase-test/env/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/donald/briefcase-test/env/lib/python3.6/site-packages/briefcase/app.py", line 477, in run
    self.install_platform_requirements()
  File "/home/donald/briefcase-test/env/lib/python3.6/site-packages/briefcase/app.py", line 298, in install_platform_requirements
    stderr=subprocess.STDOUT,
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip', 'install', '--upgrade', '--force-reinstall', '--target=/home/donald/briefcase-test/helloworld/linux/app_packages', 'toga-gtk==0.3.0.dev9']' returned non-zero exit status 1.
(env) donald@hoth:~/briefcase-test/helloworld$
```

**Comment by jlgimeno** [comment]
I know this is an old issue, but...

It may be that venv is installing older version of some tools, pip amongst them.  I would try:

```
pip install --upgrade pip wheel
```
That will update those. Then try installing cookiecutter and briefcase again.

**Comment by freakboy3742** [comment]
Looks like @jlgimeno has identified the source of the problem here. Recent versions of briefcase should be enforcing updated pip versions which will hopefully avoid this problem in future.
